version: 2
jobs:
  build:
    branches:
      only:
        - TravisCITest
    # Specify the Xcode version to use
    macos:
      xcode: "10.2.1"

    steps:
      - checkout

      - run:
          name: Detox iOS CI
          command: scripts/ci.ios.sh

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
	  
      # - store_test_results:
      #     path: test_output/report.xml
      # - store_artifacts:
      #     path: /tmp/test-results
      #     destination: scan-test-results
      # - store_artifacts:
      #     path: ~/Library/Logs/scan
      #     destination: scan-logs